### ISSUE TITLE
2020-week5_2 블랙잭 다른 풀이

### ISSUE THREAD

**Issue by sewonkimm** [sewonkimm/AlgorithmStudy#7]
[code review](https://github.com/sewonkimm/AlgorithmStudy/blob/master/2020-week5/java-jh/2020-week5-2.java)

저도 맨 처음 생각한 방법은 묵직하게 3중 for문 돌리는 거였는데요. 조합으로 풀어볼 수도 있답니다.
combination 구현해보는 것도 제안해봅니다😁

**Comment by JaeHyeonKim19** [comment]
세원님 코드를 한번 참고하려고했는데 씨쁠쁠이라 이해가 잘 안되네요 ㅠ 씨쁠쁠도 공부해보겠습니다.

combination이라하심은 순열을 말씀하시는건가요? 혹시 제 코드와 어떤 차이가 있는건지 설명해주시면 감사하겠습니다.

**Comment by sewonkimm** [comment]
c++ 에는 STL에 next_permutation 함수를 써서 구현할 수 있는데 Java는 직접 구현해야한다고 하네요...!
n장 중에 3장 뽑는 경우의 수를 next_permutation 함수를 써서 만들면 3중 for문을 작성하지 않아도 되요!

JAVA로 함수 구현하는 법은 한 번 [참고](https://mygumi.tistory.com/60)해보세요~!
